#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from radcast.experiments.restoration_eval import score_report_file


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Score a restoration report against its reference block.")
    parser.add_argument("report", type=Path, help="Path to report text generated by a restoration evaluation.")
    parser.add_argument("--ref", default="adobe", help="Reference block name inside the report.")
    parser.add_argument("--target", default="restored", help="Target block name inside the report.")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    payload = score_report_file(args.report.expanduser().resolve(), ref=args.ref, target=args.target)
    print(json.dumps(payload, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
